# fly.toml app configuration file generated for stimulus on 2023-09-14T14:39:01-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "stimulus"
primary_region = "gru"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "5000"

[deploy]
  release_command = "npm run db:migrate"
